name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: gradle

    - name: Setup NDK r15c
      uses: nttld/setup-ndk@v1.2.0
      with:
        ndk-version: r15c

    - name: Grant permissions
      run: chmod +x gradlew

    - name: Build
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: doom-apk
        path: doom/build/outputs/apk/debug/doom-debug.apk
